# Generated by Django 3.1.3 on 2021-04-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactagent',
            name='profile',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
